### ISSUE TITLE
mirai2 v0.0.8 bot发送消息时出错

### ISSUE THREAD

**Issue by RainChain-Zero** [ieew/nonebot_adapter_mirai2#11]
~~又是我，别打我~~

将本adapter更新至0.0.8版本后，bot无法正常发送信息

#### 最简源码
```
matcher=on_startswith("nb2")
@matcher.handle()
async def _():
    await matcher.finish("success")
```
#### 控制台ERROR：

![图片](https://user-images.githubusercontent.com/74779439/156907311-f714c06d-ef4e-44ee-949a-f574b8d6f0b8.png)

#### 相关配置

nb侧配置

```
HOST=127.0.0.1
PORT=8081
driver=nonebot.drivers.fastapi+nonebot.drivers.httpx+nonebot.drivers.websockets
MIRAI_HOST=127.0.0.1
MIRAI_PORT=8080
MIRAI_VERIFY_KEY=INITKEYr61MGWpM
MIRAI_QQ=["xxxxxxx"]
```
> 尝试过按照config.py内的指示将mirai_qq修改为int，无果

mirai-api-http 2.4.0
```
adapters: 
  - ws
debug: false
enableVerify: false
verifyKey: INITKEYr61MGWpM
singleMode: false
cacheSize: 4096
adapterSettings: {
  ws:
    host: 127.0.0.1
    port: 8080
    reservedSyncId: -1
}
```
> 能够成功建立连接，之前的群聊图片bug也没问题了，但发送消息出错
现已降级到0.0.6
~~如果是我的问题，请狠狠鞭打我~~

**辛苦了！！**

**Comment by ieew** [comment]
不，其实是我的问题，你可以先暂时停留在0.0.5版本

**Comment by RainChain-Zero** [comment]
谢谢解答(

**Comment by ieew** [comment]
新上传了一个dev分支，你可以试试dev分支的adapter，如果没有问题我就合并发新版了 0.0

**Comment by RainChain-Zero** [comment]
都没问题了！好耶！
