### ISSUE TITLE
接收到@消息会报错

### ISSUE THREAD

**Issue by fatinghenji** [ieew/nonebot_adapter_mirai2#14]
nb控制台日志：
```python3
Task exception was never retrieved
future: <Task finished name='Task-86' coro=<process_event() done, defined at /usr/local/lib/python3.8/dist-packages/nonebot/adapters/mirai2/utils.py:96> exception=AttributeError("'NoneType' object has no attribute 'type'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/mirai2/utils.py", line 103, in process_event
    event = process_at(bot, event)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/mirai2/utils.py", line 60, in process_at
    at = event.message_chain.extract_first(MessageType.AT)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/mirai2/message.py", line 408, in extract_first
    if (not type) or (first.type in type):
AttributeError: 'NoneType' object has no attribute 'type'
```
nb版本：`2.0.0-beta.2`
mirai-http-api版本：`2.4.0`

**Comment by ieew** [comment]
大概知道什么回事了，不过还是希望你提供一下触发这个bug时的消息内容

**Comment by fatinghenji** [comment]
> 大概知道什么回事了，不过还是希望你提供一下触发这个bug时的消息内容

@bot 搜图

**Comment by fatinghenji** [comment]
补充：
貌似不仅仅是@消息报错，gif图片也报错
![image](https://user-images.githubusercontent.com/37131177/157434569-d45ab990-49d1-44e5-b4e6-fa7cf3d71cac.png)
注意右上及左下两个窗口

**Comment by ieew** [comment]
我这并不能测试出你的bug...

**Comment by fatinghenji** [comment]
（太怪了，需要我进一步提供什么吗？

**Comment by ieew** [comment]
提供一下你的adapter版本号以及该功能所属插件的指令或消息装饰器的代码之类的让我看看吧.....（你也可以在nb群找一个叫 pip install mirai2 的人(类似名字的人)，他就是我

**Comment by ieew** [comment]
我说说我目前的测试环境。
mirai-api-http: 2.5.0
adapter: 0.0.9
nonebot2: 2.0.0b2

**Comment by fatinghenji** [comment]
nonebot-adapter-mirai2     0.0.6
可能是adapter版本问题，礼问升级命令

**Comment by ieew** [comment]
pip install nonebot_adapter_mirai2 --upgrade
或者在 `pyproject.toml` 中指定新版本的版本号

**Comment by fatinghenji** [comment]
> `pip install nonebot_adapter_mirai2 --upgrade` 或者在 `pyproject.toml` 中指定新版本的版本号

升级成功了，但是出现了和[issue13](https://github.com/ieew/nonebot_adapter_mirai2/issues/13)相同的问题

**Comment by fatinghenji** [comment]
申请您为好友了，麻烦您通过一下
