### ISSUE TITLE
wiki中的.env配置项缺失

### ISSUE THREAD

**Issue by inscripoem** [ieew/nonebot_adapter_mirai2#18]
在2.0.0-beta.2版本下按照wiki中的.env文件格式编辑运行之后会报下面的错  
<pre>（上略）
pydantic.error_wrappers.ValidationError: 1 validation error for Config
mirai_qq
  field required (type=value_error.missing)</pre>
经过排查后是Config类中的mirai_qq配置项没有传入，如果说SUPERUSER是NoneBot的超级用户，那么`.env`中应该含有与其值相同的MIRAI_QQ配置项，实测加入后也解决了报错的问题，请问这是wiki中的疏漏吗？

**Comment by ieew** [comment]
检查了一下，确实如此，目前已修改 `wiki`
