### ISSUE TITLE
通过加群申请或拒绝加群申请报错

### ISSUE THREAD

**Issue by QuBenhao** [ieew/nonebot_adapter_mirai2#20]
您好，请问bot在处理加群请求的时候报这个错是为什么呀
```
       return await bot.api.post('/resp/memberJoinRequestEvent',
AttributeError: 'functools.partial' object has no attribute 'post'
```
通过和拒绝都一样，看起来是我没有post方法

调用的代码是
```python3
    await event.approve(bot)
```
有判断event是MemberJoinRequestEvent类

**Comment by ieew** [comment]
该问题已经解决于 `dev` 分支，你可以试用一下 `dev` 分支的 `adapter ` 。如果测试后一切正常我就合并分支并发版了

**Comment by QuBenhao** [comment]
> 该问题已经解决于 `dev` 分支，你可以试用一下 `dev` 分支的 `adapter` 。如果测试后一切正常我就合并分支并发版了

@ieew 测试成功，感谢
