### ISSUE TITLE
quote消息类型的一点疑问

### ISSUE THREAD

**Issue by RainChain-Zero** [ieew/nonebot_adapter_mirai2#22]
尝试使用以下代码构造回复消息时提示错误信息
```
await test.finish(MessageSegment.quote(event.source.id,0,这里是sender_id,bot.self_id,MessageChain("test")))
```
Error
```
nonebot.exception.ActionFailed: mirai V2 | {'code': 500, 'msg': 'message is empty'}
```
附完整log
![图片](https://user-images.githubusercontent.com/74779439/163685256-3df70d0a-8efc-41e7-907a-1a9748797958.png)
![图片](https://user-images.githubusercontent.com/74779439/163685261-da2e07a8-fc61-4cbb-aee5-cb4d4b319f60.png)

adapter V0.0.10
mah  V2.4

请问是我的使用方法存在问题吗，十分感谢！

**Comment by ieew** [comment]
每条消息都有专门的消息 `id` ，如果想要回复消息，你需要将消息 `id` 传入参数 `quote` 。就像这样：
```python
@message.handle()
async def _(bot: Bot, event: GroupMessage):
    await message.send(消息内容, quote=消息id)
```

**Q：为什么要这样设计？**
**A：因为 `mirai_api_http` 就是这样设计的**

**Comment by RainChain-Zero** [comment]
> 每条消息都有专门的消息 `id` ，如果想要回复消息，你需要将消息 `id` 传入参数 `quote` 。就像这样：
> 
> ```python
> @message.handle()
> async def _(bot: Bot, event: GroupMessage):
>     await message.send(消息内容, quote=消息id)
> ```
> 
> **Q：为什么要这样设计？** **A：因为 `mirai_api_http` 就是这样设计的**

已经成功，感谢解答！
