### ISSUE TITLE
无法连接到mirai-api-http-v2.5.0

### ISSUE THREAD

**Issue by Arcsion** [ieew/nonebot_adapter_mirai2#24]
`nonebot_adapter_mirai2 0.0.10`及`nonebot_adapter_mirai2 0.0.11`无法与`mirai-api-http-v2.5.0`建立连接
`0.0.10`连接`mirai-api-http-v2.5.0`提示`Connection Error`
`0.0.11`连接`mirai-api-http-v2.5.0`提示`Connection Timeout`
这两个版本连接`mirai-api-http-v2.4.0`均正常

**Comment by ieew** [comment]
很遗憾我无法复现该问题，我本地测试了 `mirai2` + `mirai-api-http-v2.5.0` 一切正常。但我发现确实存在你的这种现象，目前暂时不清楚原因为何。该问题将维持观望状态不会被关闭。

**Comment by ieew** [comment]
到目前为止难以复现该问题，目前暂时认为可能和设备的网络环境设置有关。因此决定关闭该问题
