### ISSUE TITLE
无法接收任何消息

### ISSUE THREAD

**Issue by zmdyy0318** [ieew/nonebot_adapter_mirai2#29]
nonebot2-2.0.0b4
nonebot_adapter_mirai2
python3.8.9
mac
现象：接收消息时messagechain为空，经过定位，这一步返回为空。
进入parser_obj_as前：
![96A1100A-D5C4-447E-9C15-AAC84C2638E6](https://user-images.githubusercontent.com/16699676/177460860-10e519e5-464f-44da-919e-c12a02100a0d.png)
进入parser_obj_as后：
![0D289D38-104C-46D8-BC81-47D619A71125](https://user-images.githubusercontent.com/16699676/177460931-a552601c-9cb6-4987-8dba-f14138121f5f.png)

**Comment by ieew** [comment]
我在 `dev` 分支新提交了一点东西，你试试看是否解决了 `nonebot2.0.0b4` 的适配问题，我本地看起来似乎是没问题了。
