### ISSUE TITLE
mirai2适配器下发送本地语音有问题

### ISSUE THREAD

**Issue by PIPIKAI** [ieew/nonebot_adapter_mirai2#33]
**描述问题：**
mirai2适配器下发送本地语音有问题

**如何复现？**
```python
from nonebot.adapters.mirai2.message import MessageSegment

await command.finish(MessageSegment.voice(path="/../../xxx.mp3"))
```

不知道是什么问题，试了下上传本地图片是没问题的

**环境信息：**

 - OS: Linux
 - Python Version: 3.10.5
 - Nonebot Version:  2.0

**Comment by ieew** [comment]
提供一下错误现象(另外提醒一下，如果你使用 path 的话要考虑你的路径应该是相对于 mirai-console 的路径，而不是 相对于 nonebot 的路径，如果感觉处理费力的话建议使用base64和url参数传递
