### ISSUE TITLE
无法正确处理开头不是@的群聊消息

### ISSUE THREAD

**Issue by KamijoToma** [ieew/nonebot_adapter_mirai2#37]
在做机器人的时候偶然发现这个适配器不能正确处理开头不是@的消息。

例如，当用户发送`Hello @Bot`的时候，接收到的`event`中的`to_me`属性为`False`，而不是`True`

适配器版本`0.0.17`

**Comment by ieew** [comment]
确实存在这个问题，但是这样的话最好还是改一下，在找到at机器人的元素时不要把它从消息链中弹出。
