### ISSUE TITLE
开头带at的消息不能正常分配给on_command

### ISSUE THREAD

**Issue by zzjjbb** [ieew/nonebot_adapter_mirai2#48]
- 预期情况：
  bot收到一条消息`@bot /帮助`，带有`on_command("帮助", rule=to_me())`的响应器会被执行
- 实际情况：
  `on_command("帮助", rule=to_me())`不会执行，`on_command("帮助")`也不会执行。但是收到`/帮助 @bot`时会执行

以前没有这个问题，原因应该是https://github.com/ieew/nonebot_adapter_mirai2/issues/37#issuecomment-1342243619 ，需要把at弹出消息链，`on_command`才能正常工作。（或者难道是`on_command`本来就不应该响应这种消息，以前是不正常的，现在才是正确的？）

**Comment by ieew** [comment]
我个人认为at元素作为消息的一部分理应不被删除才对，但是onebot会在某些情况下删除at元素。因此这个问题需要探讨，我暂时还无法确定哪个才是正确的。

**Comment by ieew** [comment]
@zzjjbb 询问了一下ddl，他表示仅仅是get message方法需要是去除at之后的，这个方法将会用于命令触发判断，而其他地方并没有要求。我看看应该怎么调整合适
