### ISSUE TITLE
无法解析域名

### ISSUE THREAD

**Issue by ranchengpan51205** [ieew/nonebot_adapter_mirai2#54]
![image](https://user-images.githubusercontent.com/127505178/228196208-0031361a-f274-4869-beaf-a5ebed3d6e6b.png)
![image](https://user-images.githubusercontent.com/127505178/228196524-b25f1604-4008-4eb2-ad29-5a4ce82b3f41.png)
二图使用的公网IP，一图是公网IP绑定的ddns域名

**Comment by ieew** [comment]
以下是 mirai2 构建 url 的部分
https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L117-L118

构建的 url 是在这里交给 driver 发起连接的
https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L130-L144

因此 nonebot-adapter-mirai2 并没有自己发起连接，如果产生网络问题大概和 nonebot-adapter-mirai2 没什么关系。
如果你认为和 nonebot-adapter-mirai2 有关，还请提供更详细的调试信息

**Comment by ranchengpan51205** [comment]
> 以下是 mirai2 构建 url 的部分
> 
> https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L117-L118
> 
> 构建的 url 是在这里交给 driver 发起连接的
> 
> https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L130-L144
> 
> 因此 nonebot-adapter-mirai2 并没有自己发起连接，如果产生网络问题大概和 nonebot-adapter-mirai2 没什么关系。 如果你认为和 nonebot-adapter-mirai2 有关，还请提供更详细的调试信息


有解决办法吗？还是说单纯问题不在本项目上？

**Comment by ieew** [comment]
> > 以下是 mirai2 构建 url 的部分
> > https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L117-L118
> > 
> > 构建的 url 是在这里交给 driver 发起连接的
> > https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L130-L144
> > 
> > 因此 nonebot-adapter-mirai2 并没有自己发起连接，如果产生网络问题大概和 nonebot-adapter-mirai2 没什么关系。 如果你认为和 nonebot-adapter-mirai2 有关，还请提供更详细的调试信息
> 
> 有解决办法吗？还是说单纯问题不在本项目上？

信息量太少，没法给出建议。

**Comment by ranchengpan51205** [comment]
> > > 以下是 mirai2 构建 url 的部分
> > > https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L117-L118
> > > 
> > > 构建的 url 是在这里交给 driver 发起连接的
> > > https://github.com/ieew/nonebot_adapter_mirai2/blob/e08c4a2be46542753ba7e8edb2d0a0f2bd612dca/nonebot/adapters/mirai2/adapter.py#L130-L144
> > > 
> > > 因此 nonebot-adapter-mirai2 并没有自己发起连接，如果产生网络问题大概和 nonebot-adapter-mirai2 没什么关系。 如果你认为和 nonebot-adapter-mirai2 有关，还请提供更详细的调试信息
> > 
> > 
> > 有解决办法吗？还是说单纯问题不在本项目上？
> 
> 信息量太少，没法给出建议。

正常来讲是能够解析域名的吗？
我这边按照官方教程 nb create 选择的 FastAPI + websocket
直接单选的mirai2 进行安装的 然后配置的 .env.prod
没有做任何其他配置，并且由于域名ip是动态的，所以只能使用域名连接 因此才遇到的这个问题
刚刚从新使用nb create的项目也是无法使用连接域名  改为域名的ip却可以正常连接

.env.prod 配置文件如下
DRIVER=~fastapi+~websockets                                                     
VERIFY_KEY=123456789 # MiraiApiHttp2 配置文件里的 token                         
                                                                                
MIRAI_HOST=nas.xxxxx.site  # MiraiApiHttp2 的 ip             **域名也确定是正确的，但是ipv6丢包，但是v4可以ping通 **                   
MIRAI_PORT=2084  # MiraiApiHttp2 的端口                                         
MIRAI_QQ=["2084XXXXX"]  # Mirai 上已经登录的 qq 号    **QQ号是正确的  我故意修改为的X**                          
SUPERUSERS=[]  # nonebot2 的超管(也可理解为bot的主人什么的)                                                                    
![微信截图_20230423143226](https://user-images.githubusercontent.com/127505178/233823813-0a66aacf-a4b6-40bb-84c9-f723e836c4f2.png)

**Comment by ieew** [comment]
@ranchengpan51205 建议检查一下端口是否畅通，我比较怀疑端口是否畅通的问题，因为 ping 的通并不代表端口一定畅通。

另：正常来说应该是不会出现域名无法连接但是使用 ip 就可以连接的情况的。

**Comment by ieew** [comment]
> @ranchengpan51205 建议检查一下端口是否畅通，我比较怀疑端口是否畅通的问题，因为 ping 的通并不代表端口一定畅通。
> 
> 另：正常来说应该是不会出现域名无法连接但是使用 ip 就可以连接的情况的。

突然想起来，我得解释一下，主要关注的是你的端口是否对连入请求的header有要求什么的

**Comment by ranchengpan51205** [comment]
已解决
ipv6连接超时导致的
