### ISSUE TITLE
群聊发送图片出现错误

### ISSUE THREAD

**Issue by RainChain-Zero** [ieew/nonebot_adapter_mirai2#9]
RT.在群聊中发送图片，控制台显示如下信息
![图片](https://user-images.githubusercontent.com/74779439/156816699-019569ed-137a-48b6-aa0b-640d83ed598b.png)

**Comment by ieew** [comment]
提供一下你的mirai-api-http版本号，以及发送图片部分的源码等信息。
目前本 adapter 还未完全支持最新的 2.4 版 mirai-api-http 而老版本的 mirai-api-http 我自己测试是可以正常发图片的。

**Comment by RainChain-Zero** [comment]
> 提供一下你的mirai-api-http版本号，以及发送图片部分的源码等信息。 目前本 adapter 还未完全支持最新的 2.4 版 mirai-api-http 而老版本的 mirai-api-http 我自己测试是可以正常发图片的。

非常抱歉，是我描述不够准确，出现上述错误是用户在群聊中发送了图片信息（如表情包等），私聊无误。
mirai-api-http是2.4版，或许是还未支持的部分，十分感谢您的解答
